version: '3.8'
services:
    postgres:
        container_name: postgres_db
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=library_db
        ports:
            - 5000:5432
        networks: 
            - library_back
    library_back:
        build:
            context: library_back/
            dockerfile: Dockerfile
        container_name: library_back
        environment:
            - DJANGO_SETTINGS_MODULE=src.settings
            - POSTGRES_DB=library_db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
        ports:
            - 8000:8000
        depends_on:
            - postgres
        volumes:
            - ./library_back:/var/www
        networks: 
            - library_back

networks:
    library_back: